### ISSUE TITLE
Running the artifactory-ha.yml image fails to start Nginx

### ISSUE THREAD

**Issue by patbat95008** [jfrog/artifactory-docker-examples#95] opened 2018-07-31 17:40 UTC
Steps to reproduce:
1. Save the docker-compose yaml file:
**wget https://raw.githubusercontent.com/jfrog/artifactory-docker-examples/master/docker-compose/artifactory-ha.yml**
2. Run docker-compose:
docker-compose up

Note the Nginx gets stuck in a restart loop as the artifactory.conf file is not set correctly

**nginx                | 2018-07-31 17:37:34  [146 entrypoint-nginx.sh] Preparing to run Nginx in Docker
nginx                | 2018-07-31 17:37:34   [11 entrypoint-nginx.sh] Dockerfile for this image can found inside the container.
nginx                | 2018-07-31 17:37:34   [12 entrypoint-nginx.sh] To view the Dockerfile: 'cat /docker/nginx-artifactory-pro/Dockerfile.nginx'.
nginx                | 2018-07-31 17:37:34   [69 entrypoint-nginx.sh] Setting up directories if missing
nginx                | 2018-07-31 17:37:34  [140 entrypoint-nginx.sh] Artifactory configuration already in /var/opt/jfrog/nginx/conf.d/artifactory.conf
nginx                | 2018-07-31 17:37:34   [28 entrypoint-nginx.sh] SSL is set. Setting up SSL certificate and key
nginx                | 2018-07-31 17:37:34   [41 entrypoint-nginx.sh] Found SSL_KEY /var/opt/jfrog/nginx/ssl/example.key
nginx                | 2018-07-31 17:37:34   [43 entrypoint-nginx.sh] Found SSL_PEM /var/opt/jfrog/nginx/ssl/example.pem
nginx                | 2018-07-31 17:37:34   [54 entrypoint-nginx.sh] Updating /var/opt/jfrog/nginx/conf.d/artifactory.conf with /var/opt/jfrog/nginx/ssl/example.key and /var/opt/jfrog/nginx/ssl/example.pem
nginx                | 2018-07-31 17:37:34   [77 entrypoint-nginx.sh] Setting permissions on Nginx directories
nginx                | 2018-07-31 17:37:34  [158 entrypoint-nginx.sh] Starting updateConf.sh in the background
nginx                | 2018-07-31 17:37:34  [163 entrypoint-nginx.sh] Starting nginx daemon...
nginx                | nginx: [emerg] host not found in upstream "artifactory" in /etc/nginx/conf.d/artifactory.conf:27**

This is after both node1 and node2 have started. It looks like the Nginx node cannot communicate with the upstream URLs it is configured for. 

**jfrog@jfrog:~/downloads/art-test$ docker-compose ps
      Name                     Command                 State              Ports         
----------------------------------------------------------------------------------------
artifactory-node1   /entrypoint-artifactory.sh       Up           0.0.0.0:8081->8081/tcp
artifactory-node2   /entrypoint-artifactory.sh       Up           0.0.0.0:8082->8081/tcp
nginx               /bin/sh -c /entrypoint-ngi ...   Restarting                         
postgresql          /docker-entrypoint.sh postgres   Up           0.0.0.0:5432->5432/tcp**

Curls from within the Nginx container fail to reach the running Artifactory nodes on both the base_url and IP addresses.

**Comment by ankushchadha** [comment] 2018-08-01 15:59
@jainishshah17 - can you take a look?

**Comment by jainishshah17** [comment] 2018-08-01 18:41
@patbat95008 Following this steps will help. https://github.com/jfrog/artifactory-docker-examples/tree/master/docker-compose#artifactory-ha

**Comment by patbat95008** [comment] 2018-08-01 19:07
After some troubleshooting I was able to get this to work using the following steps:

0. Clean the /data directory and remove the previous docker containers
$ docker ps -a
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                        PORTS               NAMES
75eee42c6747        docker.bintray.io/jfrog/nginx-artifactory-pro:6.1.0   "/bin/sh -c /entrypo…"   24 hours ago        Restarting (1) 24 hours ago                       nginx
103fd448e2b8        docker.bintray.io/jfrog/artifactory-pro:6.1.0         "/entrypoint-artifac…"   24 hours ago        Exited (143) 24 hours ago                         artifactory-node2

$ docker rm 103fd448e2b8

1. git clone the entire artifactory-docker-examples project

2. Run the “prepareHostEnv.sh” script:
$ sudo ./prepareHostEnv.sh -t ha -c
Are you sure you want to remove existing /data [y/n]: y
Removing old /data
Creating /data
Copying needed files to directories
Artifactory configuration files
Nginx Artifactory configuration

3. Run docker-compose:
$ docker-compose -f artifactory-ha.yml up

**Comment by esn89** [comment] 2018-10-05 11:11
I have the same issue here.

I think it might be because of this:

```[root@ip-10-4-85-232 artifactory]# ./prepareHostEnv.sh -t ha-shared-data
./prepareHostEnv.sh: line 117: [: =: unary operator expected
Creating /data
Copying needed files to directories
Artifactory configuration files
Nginx Artifactory configuration
**cp: cannot stat ‘./../files/nginx/conf.d/ha-shared-data/*’: No such file or directory**
Setting needed ownerships on /data```

**Comment by esn89** [comment] 2018-10-08 08:40
@eldada 
Unfortunately, it is still failing:
```
[root@mybox]# ./prepareHostEnv.sh -t ha-shared-data -c
Are you sure you want to remove existing /data [y/n]: y
Removing old /data
Creating /data
First setup. Setting FIRST_SETUP=true
Copying needed files to directories
Artifactory configuration files
Nginx Artifactory configuration
cp: cannot stat ‘./../../files/nginx/conf.d/ha-shared-data/*’: No such file or directory

ERROR: Copy failed

[root@ip-10-4-85-53 artifactory]# git rev-parse HEAD
cea04c5a5ed4cc046e372eebfca6060d6bb72ba4
```

**Comment by eldada** [comment] 2018-10-08 08:43
@esn89 - checking

**Comment by eldada** [comment] 2018-10-08 08:49
@esn89 - a small fix was committed. Can you check now?

**Closed** 2018-10-09 05:40 UTC

**Comment by yiwu1** [comment] 2019-12-04 03:00
I meet same when deploying to kubectl cluster, with HA node 1 and HA node 2 started up successfully, but get **"[emerg] host not found in upstream "artifactory" in /etc/nginx/conf.d/artifactory.conf:31"**.Any root cause can share?
kubectl logs nginx-d554978d9-kwrw5
Using deprecated password for user _internal.
2019-12-03 08:17:48  [138 entrypoint-nginx.sh] Preparing to run Nginx in Docker
2019-12-03 08:17:48   [11 entrypoint-nginx.sh] Dockerfile for this image can found inside the container.
2019-12-03 08:17:48   [12 entrypoint-nginx.sh] To view the Dockerfile: 'cat /docker/nginx-artifactory-pro/Dockerfile.nginx'.
2019-12-03 08:17:48   [68 entrypoint-nginx.sh] Setting up directories if missing
2019-12-03 08:17:48  [132 entrypoint-nginx.sh] Artifactory configuration already in /var/opt/jfrog/nginx/conf.d/artifactory.conf
2019-12-03 08:17:48   [27 entrypoint-nginx.sh] SSL is set. Setting up SSL certificate and key
2019-12-03 08:17:49   [40 entrypoint-nginx.sh] Found SSL_KEY /var/opt/jfrog/nginx/ssl/example.key
2019-12-03 08:17:49   [41 entrypoint-nginx.sh] Found SSL_CRT /var/opt/jfrog/nginx/ssl/example.crt
2019-12-03 08:17:49   [53 entrypoint-nginx.sh] Updating /var/opt/jfrog/nginx/conf.d/artifactory.conf with /var/opt/jfrog/nginx/ssl/example.key and /var/opt/jfrog/nginx/ssl/example.crt
2019-12-03 08:17:49  [149 entrypoint-nginx.sh] Starting updateConf.sh in the background
Using deprecated password for user _internal.
2019-12-03 08:17:49  [154 entrypoint-nginx.sh] Starting nginx daemon...
nginx: [emerg] host not found in upstream "artifactory" in /etc/nginx/conf.d/artifactory.conf:31
