### ISSUE TITLE
HA not starting with 6.2

### ISSUE THREAD

**Issue by strategicenterprisesolutions** [jfrog/artifactory-docker-examples#101] opened 2018-08-14 01:04 UTC
Seems to have directory permission issues as well as nginx config

OS: CentOS 7.5 (SELINUX disabled)
docker-compose: 1.22.0
docker-ce: 18.06

will post logs shortly..

**Comment by strategicenterprisesolutions** [comment] 2018-08-14 01:05
Steps to reproduce:
New VM with Centos 7.5

git clone https://github.com/jfrog/artifactory-docker-examples.git
cd artifactory-docker-examples/docker-compose/
./prepareHostEnv.sh -t ha -c
docker-compose -f artifactory-ha.yml up -d

**Comment by eldada** [comment] 2018-08-14 10:37
@strategicenterprisesolutions - you are right. This is caused by the new feature in 6.2 that now artifactory starts and runs as a non-root user. This means you have to give it permissions before starting it up.
I will work on updating `./prepareHostEnv.sh` to add support for it.

**Comment by eldada** [comment] 2018-08-14 13:49
@strategicenterprisesolutions - thanks for the feedback.
With Artifactory 6.2, we introduced true non-root containers for Artifactory and Nginx. See [data persistency](https://www.jfrog.com/confluence/display/RTF/Installing+with+Docker#InstallingwithDocker-ManagingDataPersistence) section in Artifactory wiki.
We'll provide a fix to the `prepareHostEnv.sh` to reflect this feature.

**Comment by strategicenterprisesolutions** [comment] 2018-08-15 00:49
Thanks. I was able to get to past this issue by adding these entries to prepareHostEnv.sh (line 166/167)
chown -R 1030:1030 ${ROOT_DATA_DIR}/artifactory
chown -R 104:107 ${ROOT_DATA_DIR}/nginx

**Comment by eldada** [comment] 2018-08-15 05:03
Yes. This is the correct solution. We have a pull request with a similar change to this 😄

**Comment by eldada** [comment] 2018-08-15 05:42
Fix merged. Closing. @strategicenterprisesolutions - let us know if you see any issues.

**Closed by eldada** 2018-08-15 05:42 UTC
