### ISSUE TITLE
ha propagation error on non-primary nodes

### ISSUE THREAD

**Issue by subham371** [jfrog/artifactory-docker-examples#145] opened 2019-02-19 12:00 UTC
I am getting the following error on the non-primary nodes, I am new to artifactory ha setup any help with regards to this will be appreciated.

```
[art-exec-6] [ERROR] (o.a.a.h.p.HaPropagationServiceImpl:346) - Error propagating event: tasksList: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.http.conn.EofSensorInputStream@45216972; line: 1, column: 2]
org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.http.conn.EofSensorInputStream@45216972; line: 1, column: 2]
        at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
        at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2090)
        at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:606)
        at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:492)
        at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
        at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2691)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1286)
        at org.codehaus.jackson.JsonParser.readValueAs(JsonParser.java:1336)
        at org.artifactory.api.jackson.JacksonReader.streamAsClass(JacksonReader.java:108)
        at org.artifactory.addon.ha.propagate.HaPropagationServiceImpl.propagateResponse(HaPropagationServiceImpl.java:341)
        at org.artifactory.addon.ha.propagate.HaPropagationServiceImpl.lambda$getServerResponse$2(HaPropagationServiceImpl.java:300)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.artifactory.concurrent.ArtifactoryRunnable.run(ArtifactoryRunnable.java:50)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-02-19 11:34:36,827 [art-exec-5] [ERROR] (o.a.a.h.p.HaPropagationServiceImpl:208) - Failed to propogate - sleeping...
```

**Comment by eldada** [comment] 2019-02-19 14:38
@subham371 - please provide some details on the way you set up this environment. A way for us to reproduce.
Are you using the examples from this repository?
The error `Unexpected character ('<' (code 60))` seems to hint something in the configuration is messed up.

**Comment by ShreyasNBS** [comment] 2019-11-08 13:25
@subham371 @eldada Did you manage to resolve this? I am getting same error

**Comment by justin-cn-to** [comment] 2019-11-27 19:15
We ran into a similar issue, and we were able to resolve it by setting up the `ha-node.properties` properly.

`context.url` should be set to `http://<private ip>:8081/artifactory`
and
`hazelcast.interface` should also be set to `<private ip>` as well.

We eventually figured out by reading this [JFrog documentation](https://www.jfrog.com/confluence/display/RTF/HA+Installation+and+Setup), I suppose JFrog could've documented this part better...

**Comment by JfrogPrasanna** [comment] 2020-04-30 03:51
Closing this due to the age. Please re-open a new one in JFrog support tickets. This  repo is being deprecated.

**Closed by JfrogPrasanna** 2020-04-30 03:51 UTC
